### ISSUE TITLE
Set up TypeScript Environment

### ISSUE THREAD

**Issue by zaki-yama** [mashmatrix/react-lightning-design-system#290]
ref. #289 

Construct TypeScript environment.
In addition to transpile to current ES5 format (with babel-preset-env), we need to build as ES Modules format so that the users can use Tree-shaking with webpack, Rollup, etc.

## TODO

- [ ] Update Babel's version to 7 to support TypeScript
- [ ] Enable to transpile `.ts` files to ES5 format
- [ ] Enable to transpile `.ts` files to ES Modules format
- [ ] Enable to run Jest
- [ ] Enable to use ESLint (and Prettier, if needed)
